from . import base

MAX_PRIORITY = 10
PRIORITY_SUBMIT = 8
PRIORITY_REJUDGE_SINGLE = 5
PRIORITY_REJUDGE_BATCH = 3
PRIORITY_NONE = 0
ASSISTING_DATA_DIR = '/assisting_data'
CUSTOMIZED_JUDGE_FUNCTION_NAME = 'judge_function'
CUSTOMIZED_JUDGE_CPP_TESTLIB_SCORE_FILENAME = 'score.txt'
CUSTOMIZED_JUDGE_CPP_TESTLIB_MEMORY_LIMIT: base.KiloBytes = 1_000_000
CUSTOMIZED_JUDGE_CPP_TESTLIB_TIME_LIMIT: base.MilliSeconds = 10_000
