# Decrease the maximum line length to 79 characters.
line-length = 120

[per-file-ignores]
    # imported but unused
    "__init__.py" = ["F401", "E402"]
    "main.py" = ["E402"]
    "persistence/database/*" = ["E501"]
    "persistence/database/base.py" = ["E402"]
